//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACLFunction
    {
        public ACLFunction()
        {
            this.ACLActions = new HashSet<ACLAction>();
        }
    
        public int FunctionID { get; set; }
        public string FunctionName { get; set; }
        public Nullable<int> FunctionOrder { get; set; }
    
        public virtual ICollection<ACLAction> ACLActions { get; set; }
    }
}
