//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Accounts = new HashSet<Account>();
            this.ACLRoles = new HashSet<ACLRole>();
            this.Calls = new HashSet<Call>();
            this.Campaigns = new HashSet<Campaign>();
            this.Cases = new HashSet<Case>();
            this.CompanyModules = new HashSet<CompanyModule>();
            this.Contacts = new HashSet<Contact>();
            this.Documents = new HashSet<Document>();
            this.Emails = new HashSet<Email>();
            this.Invoices = new HashSet<Invoice>();
            this.Leads = new HashSet<Lead>();
            this.Meetings = new HashSet<Meeting>();
            this.Notifications = new HashSet<Notification>();
            this.Opportunities = new HashSet<Opportunity>();
            this.Orders = new HashSet<Order>();
            this.Payments = new HashSet<Payment>();
            this.Products = new HashSet<Product>();
            this.Reports = new HashSet<Report>();
            this.ShortMessages = new HashSet<ShortMessage>();
            this.ShortMessageTemplates = new HashSet<ShortMessageTemplate>();
            this.Tasks = new HashSet<Task>();
            this.Teams = new HashSet<Team>();
            this.TeamSets = new HashSet<TeamSet>();
            this.UserLogins = new HashSet<UserLogin>();
            this.Users = new HashSet<User>();
            this.Quotes = new HashSet<Quote>();
            this.Deals = new HashSet<Deal>();
            this.Notes = new HashSet<Note>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> BusinessID { get; set; }
        public string HeadOfficeAddress { get; set; }
        public Nullable<int> CompanyTypeID { get; set; }
        public string Tin { get; set; }
        public string TradeNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> BankAccount { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> DateFormatID { get; set; }
        public Nullable<int> TimeFormatID { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public Nullable<bool> OnTrial { get; set; }
        public Nullable<System.DateTime> TrialStartDate { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<ACLRole> ACLRoles { get; set; }
        public virtual BankAccountsInfo BankAccountsInfo { get; set; }
        public virtual ICollection<Call> Calls { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual DateFormat DateFormat { get; set; }
        public virtual Language Language { get; set; }
        public virtual TimeFormat TimeFormat { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        public virtual CompanyType CompanyType { get; set; }
        public virtual ICollection<CompanyModule> CompanyModules { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<Meeting> Meetings { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<ShortMessage> ShortMessages { get; set; }
        public virtual ICollection<ShortMessageTemplate> ShortMessageTemplates { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<TeamSet> TeamSets { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<Deal> Deals { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
    }
}
