//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingInvitee
    {
        public long MeetingInviteeID { get; set; }
        public Nullable<long> MeetingID { get; set; }
        public Nullable<long> InviteeID { get; set; }
        public string InviteeType { get; set; }
    
        public virtual Meeting Meeting { get; set; }
    }
}
