//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaData
    {
        public int CompanyID { get; set; }
        public int ExtensionID { get; set; }
        public string ExtLabel { get; set; }
        public string ExtDataType { get; set; }
    }
}
