//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.ACLActions = new HashSet<ACLAction>();
            this.CompanyModules = new HashSet<CompanyModule>();
            this.Reports = new HashSet<Report>();
        }
    
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> ModuleOrder { get; set; }
        public string RelativePath { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    
        public virtual ICollection<ACLAction> ACLActions { get; set; }
        public virtual ICollection<CompanyModule> CompanyModules { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}
