//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.Emails = new HashSet<Email>();
            this.ShortMessages = new HashSet<ShortMessage>();
        }
    
        public long NotificationID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> NotificationTypeID { get; set; }
        public Nullable<int> Status { get; set; }
        public string ParentType { get; set; }
        public Nullable<long> ParentID { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        public virtual ICollection<ShortMessage> ShortMessages { get; set; }
    }
}
