//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Accounts = new HashSet<Account>();
            this.ACLActions = new HashSet<ACLAction>();
            this.Calls = new HashSet<Call>();
            this.Campaigns = new HashSet<Campaign>();
            this.Cases = new HashSet<Case>();
            this.Contacts = new HashSet<Contact>();
            this.Documents = new HashSet<Document>();
            this.Emails = new HashSet<Email>();
            this.Invoices = new HashSet<Invoice>();
            this.Leads = new HashSet<Lead>();
            this.Leads1 = new HashSet<Lead>();
            this.Meetings = new HashSet<Meeting>();
            this.Opportunities = new HashSet<Opportunity>();
            this.Orders = new HashSet<Order>();
            this.Reports = new HashSet<Report>();
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
            this.Tasks2 = new HashSet<Task>();
            this.UserLogins = new HashSet<UserLogin>();
            this.Users1 = new HashSet<User>();
            this.Quotes = new HashSet<Quote>();
            this.Deals = new HashSet<Deal>();
            this.Notes = new HashSet<Note>();
            this.Notes1 = new HashSet<Note>();
            this.Notes2 = new HashSet<Note>();
        }
    
        public long UserID { get; set; }
        public int CompanyID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> PasswordFormat { get; set; }
        public string PasswordSalt { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public Nullable<long> ReportsTo { get; set; }
        public string MobilePhone { get; set; }
        public string OfficePhone { get; set; }
        public string HomePhone { get; set; }
        public string OtherPhone { get; set; }
        public string Fax { get; set; }
        public string PrimaryEmail { get; set; }
        public string AlternateEmail { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string MessengerType { get; set; }
        public string MessengerID { get; set; }
        public string FacebookID { get; set; }
        public string NationalID { get; set; }
        public string DrivingLicense { get; set; }
        public string PassportNo { get; set; }
        public string SocialSecurityNo { get; set; }
        public string Image { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<System.Guid> ActivationID { get; set; }
        public Nullable<long> TeamID { get; set; }
        public Nullable<int> TeamSetID { get; set; }
        public string GlobalUserID { get; set; }
        public string ApplicationUserID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public Nullable<System.DateTime> LastLockoutDate { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
        public Nullable<System.DateTime> FailedPasswordAttemptWindowStart { get; set; }
        public Nullable<int> FailedSecurityAnswerCount { get; set; }
        public Nullable<System.DateTime> FailedSecurityAnswerWindowsStart { get; set; }
        public Nullable<bool> PortalOnly { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsAdminDelegate { get; set; }
        public Nullable<bool> ReceiveNotifications { get; set; }
        public Nullable<bool> IsFirstLogin { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<ACLAction> ACLActions { get; set; }
        public virtual ACLRole ACLRole { get; set; }
        public virtual ICollection<Call> Calls { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<Case> Cases { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Lead> Leads { get; set; }
        public virtual ICollection<Lead> Leads1 { get; set; }
        public virtual ICollection<Meeting> Meetings { get; set; }
        public virtual ICollection<Opportunity> Opportunities { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Task> Tasks1 { get; set; }
        public virtual ICollection<Task> Tasks2 { get; set; }
        public virtual Team Team { get; set; }
        public virtual TeamSet TeamSet { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<User> Users1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Quote> Quotes { get; set; }
        public virtual ICollection<Deal> Deals { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<Note> Notes1 { get; set; }
        public virtual ICollection<Note> Notes2 { get; set; }
    }
}
