//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountsInfo
    {
        public BankAccountsInfo()
        {
            this.Companies = new HashSet<Company>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int BankAccountID { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountType { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
