//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public long CaseID { get; set; }
        public int CompanyID { get; set; }
        public string CaseNumber { get; set; }
        public string Subject { get; set; }
        public Nullable<long> AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Resolution { get; set; }
        public Nullable<long> AssignedUserID { get; set; }
        public Nullable<long> TeamID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public byte[] Timestamp { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public System.DateTime ModifiedTime { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual CasePriority CasePriority { get; set; }
        public virtual CaseStatus CaseStatus { get; set; }
        public virtual Company Company { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
    }
}
